apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mpi-operator.yaml
- custom-service.yaml
- custom-servicemonitor.yaml

patches:
- target:
    kind: Deployment
    name: mpi-operator
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mpi-operator
              topologyKey: topology.kubernetes.io/zone
    - op: add
      path: /spec/template/spec/containers/0/ports
      value:
      - containerPort: 8888
        name: metrics
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --monitoring-port=8888
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "4"
          memory: "2Gi"
