apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-operator
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: training-operator
        # replace args to only enable TFJob, PyTorchJob & XGBoostJob
        args:
        - --enable-scheme=tfjob
        - --enable-scheme=pytorchjob
        - --enable-scheme=xgboostjob
